apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: virabshetkar/notification-service:latest
          env:
            - name: MAIL_USER
              value: "user"
            - name: MAIL_PASS
              value: "pass"
            - name: MAIL_HOST
              value: "mailcatcher-service-clusterip"
            - name: MAIL_PORT
              value: "1025"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service-clusterip
spec:
  type: ClusterIP
  selector:
    app: notification-service
  ports:
    - name: notification-service
      protocol: TCP
      port: 80
      targetPort: 3000
