apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-depl
spec:
  selector:
    matchLabels:
      app: mongodb-depl
  template:
    metadata:
      labels:
        app: mongodb-depl
    spec:
      containers:
        - name: mongodb-depl
          image: mongo
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "user"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "password"
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service-clusterip
spec:
  selector:
    app: mongodb-depl
  ports:
    - port: 27017
      targetPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: mongodb-depl
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
