apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresdb-depl
spec:
  selector:
    matchLabels:
      app: postgresdb-depl
  template:
    metadata:
      labels:
        app: postgresdb-depl
    spec:
      containers:
        - name: postgresdb-depl
          image: postgres
          ports:
            - containerPort: 5432
          env: 
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_DB
              value: default
---
apiVersion: v1
kind: Service
metadata:
  name: postgresdb-clusterip
spec:
  selector:
    app: postgresdb-depl
  ports:
    - port: 5432
      targetPort: 5432
